version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - DB_PATH=/app/data/database.sqlite
    restart: unless-stopped 